FROM python:3.11-slim

WORKDIR /app

COPY generare_date_interes.py /app

COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 5000

CMD ["python", "generare_date_interes.py"]